# Generated by Django 5.2.16 on 2026-07-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('type', models.CharField(choices=[('first_review', '首次审核'), ('change_review', '变更审核')], max_length=30, verbose_name='审核类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=30, verbose_name='审核状态')),
                ('submitted_data', models.JSONField(verbose_name='提交时完整房源快照')),
                ('original_data', models.JSONField(blank=True, null=True, verbose_name='原房源快照')),
                ('changed_fields', models.JSONField(default=list, verbose_name='变更字段名列表')),
                ('reject_reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='驳回原因')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='apartments.apartment', verbose_name='关联房源')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_audits', to='users.user', verbose_name='审核管理员')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'db_table': 'audit_records',
                'indexes': [models.Index(fields=['apartment', 'deleted_at'], name='audit_recor_apartme_3214c2_idx'), models.Index(fields=['type', 'status', 'deleted_at'], name='audit_recor_type_60f226_idx'), models.Index(fields=['reviewer'], name='audit_recor_reviewe_36eaea_idx')],
            },
        ),
    ]
