# Generated by Django 5.2.16 on 2026-07-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('name', models.CharField(max_length=50, verbose_name='区划名称')),
                ('level', models.SmallIntegerField(choices=[(1, '行政区'), (2, '街道/镇')], verbose_name='层级')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='官方编码')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='districts.district', verbose_name='父级区划')),
            ],
            options={
                'verbose_name': '行政区划',
                'verbose_name_plural': '行政区划',
                'db_table': 'districts',
                'indexes': [models.Index(fields=['parent'], name='districts_parent__b48d2e_idx'), models.Index(fields=['level'], name='districts_level_a53632_idx')],
            },
        ),
    ]
