# Generated by Django 5.2.16 on 2026-07-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('name', models.CharField(max_length=50, verbose_name='公寓名称')),
                ('cover_image', models.CharField(max_length=500, verbose_name='公寓总览图 URL')),
                ('description', models.TextField(verbose_name='公寓描述')),
                ('detail_address', models.CharField(max_length=200, verbose_name='详细门牌号')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_first_review', '待首次审核'), ('first_rejected', '首次审核驳回'), ('published', '已上架')], default='draft', max_length=30, verbose_name='状态')),
                ('min_monthly_rent', models.IntegerField(blank=True, null=True, verbose_name='最低月租金（缓存）')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='districts.district', verbose_name='行政区')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='users.user', verbose_name='商家')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='street_apartments', to='districts.district', verbose_name='街道/镇')),
            ],
            options={
                'verbose_name': '公寓房源',
                'verbose_name_plural': '公寓房源',
                'db_table': 'apartments',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('name', models.CharField(max_length=50, verbose_name='房型名称')),
                ('images', models.JSONField(default=list, verbose_name='房型图片 URL 数组')),
                ('facilities', models.JSONField(default=list, verbose_name='设施编码数组')),
                ('layout_type', models.CharField(max_length=30, verbose_name='户型编码')),
                ('window_type', models.CharField(max_length=30, verbose_name='内外窗编码')),
                ('orientation', models.CharField(max_length=30, verbose_name='朝向编码')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('sort', models.IntegerField(default=0, verbose_name='展示排序')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='apartments.apartment', verbose_name='所属公寓')),
            ],
            options={
                'verbose_name': '房型',
                'verbose_name_plural': '房型',
                'db_table': 'room_types',
            },
        ),
        migrations.CreateModel(
            name='RentalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('lease_term', models.CharField(max_length=30, verbose_name='租期编码')),
                ('monthly_rent', models.IntegerField(verbose_name='月租金（元）')),
                ('payment_method', models.CharField(max_length=30, verbose_name='支付方式编码')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_plans', to='apartments.roomtype', verbose_name='所属房型')),
            ],
            options={
                'verbose_name': '租期租金方案',
                'verbose_name_plural': '租期租金方案',
                'db_table': 'rental_plans',
            },
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['landlord'], name='apartments_landlor_5ba1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['status', 'deleted_at'], name='apartments_status_43ce2b_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['district', 'deleted_at'], name='apartments_distric_578895_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['min_monthly_rent'], name='apartments_min_mon_ec9c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['apartment', 'deleted_at'], name='room_types_apartme_20c08c_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalplan',
            index=models.Index(fields=['room_type', 'deleted_at'], name='rental_plan_room_ty_aaa352_idx'),
        ),
    ]
