# Generated by Django 5.2.16 on 2026-07-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='orientation',
        ),
    ]
