# Generated by Django 5.2.16 on 2026-07-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        ('audits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('type', models.CharField(choices=[('first_rejected', '首次审核驳回'), ('change_rejected', '变更审核驳回')], max_length=30, verbose_name='消息类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('related_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_messages', to='apartments.apartment', verbose_name='关联房源')),
                ('related_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_messages', to='audits.auditrecord', verbose_name='关联审核单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.user', verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
                'db_table': 'messages',
                'indexes': [models.Index(fields=['user', 'is_read', 'deleted_at'], name='messages_user_id_a02301_idx'), models.Index(fields=['related_apartment'], name='messages_related_434757_idx')],
            },
        ),
    ]
