# Generated by Django 5.2.16 on 2026-07-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='管理员登录账号')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('hashed_password', models.CharField(max_length=255, verbose_name='加密密码')),
                ('role', models.CharField(blank=True, choices=[('tenant', '租客'), ('landlord', '商家'), ('admin', '管理员')], db_index=True, default='', max_length=20, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'indexes': [models.Index(fields=['role'], name='users_role_0ace22_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('purpose', models.CharField(choices=[('register', '注册'), ('login', '登录'), ('reset_password', '重置密码'), ('change_password', '修改密码')], max_length=20, verbose_name='用途')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('expired_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
                'db_table': 'verify_codes',
                'indexes': [models.Index(fields=['phone', 'purpose', 'created_at'], name='verify_code_phone_f7181a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='接收手机号')),
                ('template_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='短信模板 CODE')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='模板参数')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('success', '成功'), ('failed', '失败'), ('mock', '模拟')], max_length=20, verbose_name='发送状态')),
                ('response', models.TextField(blank=True, null=True, verbose_name='发送结果/错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '短信发送日志',
                'verbose_name_plural': '短信发送日志',
                'db_table': 'sms_logs',
                'indexes': [models.Index(fields=['phone', 'created_at'], name='sms_logs_phone_fb575b_idx')],
            },
        ),
    ]
