# Generated by Django 5.2.16 on 2026-07-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hashed_password',
        ),
    ]
