# Generated by Django 5.2.16 on 2026-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('category', models.CharField(max_length=30, verbose_name='字典分类')),
                ('code', models.CharField(max_length=30, verbose_name='字典编码')),
                ('label', models.CharField(max_length=50, verbose_name='展示文案')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '系统字典',
                'verbose_name_plural': '系统字典',
                'db_table': 'system_dicts',
                'indexes': [models.Index(fields=['category'], name='system_dict_categor_ae2e60_idx')],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
